parameters:
#    rami_ferientabelle.example.class: Rami\FerientabelleBundle\Example

services:
#    rami_ferientabelle.example:
#        class: %rami_ferientabelle.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
